name: Auto-deploy Website

on:
  push:
    branches: 
    - ui-revamp-authentication

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Specify your Node.js version

      - name: Build website (if needed)
        run: |
          npm install
          npm run build 
          npm run dev