name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2


      # Steps for dev branch deployment (needs npm and a dev server)
      - name: Set up Node.js
        if: github.ref == 'refs/heads/dev'
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for dev branch
        if: github.ref == 'refs/heads/dev'
        run: |
          npm install

      - name: Build and deploy dev branch to /dev subdirectory
        if: github.ref == 'refs/heads/dev'
        run: |
          npm run dev  # command for dev branch
          npm run export
          mkdir -p .temp-deployment
          cp -R out/* .temp-deployment/  # Adjust 'public' to your build output folder
          git config --global user.email "ferrufinoda2@vcu.edu"
          git config --global user.name "deHank"
          git checkout main
          mkdir -p dev
          cp -R .temp-deployment/* dev/
          rm -rf .temp-deployment
          git add .
          git commit -m "Deploy dev branch to /dev" || echo "No changes to commit"
          git push origin gh-pages
